all:
  children:
    DC1:
      children:
        spines_DC1:
          hosts:
            spine1-DC1:
            spine2-DC1:
            spine3-DC1:
        leafs_DC1:
          children:
            odd_leafs_DC1:
              hosts:
                leaf1-DC1:
                leaf3-DC1:
            even_leafs_DC1:  
              hosts:
                leaf2-DC1:
                leaf4-DC1:
        borderleafs_DC1:
          hosts:
            borderleaf1-DC1:
            borderleaf2-DC1:
        odd_leafs_DC1:
          hosts:
            leaf1-DC1:
            leaf3-DC1:
            borderleaf1-DC1:
        even_leafs_DC1:
          hosts:
            leaf2-DC1:
            leaf4-DC1:
            borderleaf2-DC1:
    DC2:
      children:
        spines_DC2:
          hosts:
            spine1-DC2:
            spine2-DC2:
            spine3-DC2:
        leafs_DC2:
          children:
            odd_leafs_DC2:
              hosts:
                leaf1-DC2:
                leaf3-DC2:
            even_leafs_DC2:  
              hosts:
                leaf2-DC2:
                leaf4-DC2:
        borderleafs_DC2:
          hosts:
            borderleaf1-DC2:
            borderleaf2-DC2:
        odd_leafs_DC2:
          hosts:
            leaf1-DC2:
            leaf3-DC2:
            borderleaf1-DC2:
        even_leafs_DC2:
          hosts:
            leaf2-DC2:
            leaf4-DC2:
            borderleaf2-DC2:
  vars:
    ansible_connection: network_cli
    ansible_network_os: eos
    ansible_become: yes
    ansible_become_method: enable
    ansible_python_interpreter: /usr/bin/python3
    ansible_user: gregg
    # ansible_password: Arista123!
    ansible_ssh_private_key_file: ~/ACE5/ace-key
