---
  - hosts: leafs_DC1
    gather_facts: no
    tasks:
    - name: Create Template
      template:
        src: "{{lookup('env','PWD')}}/templates/vlans.j2"
        dest: "{{lookup('env','PWD')}}/configs/{{inventory_hostname}}_vlans.cfg"
    - name: Upload Config
      eos_config:
        src: "{{lookup('env','PWD')}}/configs/{{inventory_hostname}}_vlans.cfg"
